### ISSUE TITLE
"sonst" directory contains non-free code

### ISSUE THREAD

**Issue by pippijn** [tauzero7/Motion4D#1]
The code in [sonst/Maple](https://github.com/tauzero7/Motion4D/tree/master/sonst/Maple) seems to be part of GRTensorII (see [this text file](https://github.com/tauzero7/Motion4D/blob/master/sonst/Maple/makeBarriolaVilenkin.txt)) which is governed by a [non-free license](https://github.com/grtensor/grtensor/blob/master/License). In particular, `Copies of GRTensor, GRTensorII, GRTensorJ and GRTensorM may not be redistributed without notice to the authors` strongly conflicts with the notion of free software per GPL-3.0, which Motion4D is governed by.

Please consider either deleting this code from the repository or asking the grtensor maintainers to publish their code under a free software license.

**Comment by tauzero7** [comment]
No, these files are NOT part of GRTensorII. The mws files are just the maple work sheets which have the same content as the txt files. They only make use of GRTensorII.
